<footer>
    <div class="container-2">
      <div class="copyright">
        <p>&#169; 2023 Green Tech Group, JSC.</p>
      </div>
      <div class="contact-info">
        <h5>Contact Info</h5>
        <ul class="contact-info-ul">
          <li><i class="fa fa-phone"></i>1-123-345-6789</li>
          <li class="iconContact"><i class="fa fa-envelope"></i><a href="mailto:103514782@swin.edu.au"
              class="contactLink">103514782@swin.edu.au</a></li>
          <li><i class="fa fa-flag"></i>123 Smith Drive, Bartimore, MD21212</li>
        </ul>
      </div>
    </div>
</footer>