        <nav class="navbar">
            <div class="left"><span id="logo1">Green</span><span id="logo2">Tech | Carreers</span></div>
            <ul class="right">
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php">Jobs</a></li>
                <li><a href="apply.php">Application</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="manage.php">Management</a></li>
                <li><a href="enhancements.php">Enhancements</a></li>
                <li><a href="enhancements2.php">Enhancements 2</a></li>
                <li><a href="phpenhancements.php">Php Enhancements</a></li>
                <li><a href="mailto:103514782@swin.edu.au">Contact Us</a></li>
            </ul>
        </nav>